#!/bin/sh

version=`date +%Y%m%d%H%M`
image=gen/image/search-$version
[ -d gen ] && rm -rf gen
mkdir -p $image/lib $image/bin gen/classes gen/dist
find src/main -name \*.java > gen/main.list
classpath="lib/run/hsqldb.jar"
javac -source 1.7 -target 1.7 -classpath "$classpath" -d gen/classes @gen/main.list
jar cvf gen/dist/search.jar -C gen/classes .
cp lib/run/* gen/dist/search.jar $image/lib
cp src/bin/* $image/bin
cp config.properties $image/config.properties
chmod +x $image/bin/*
cp README $image
tar cfz gen/dist/search.tar.gz -C gen/image .
#(cd gen/image && zip -q ../../gen/dist/search.zip -r .)

echo search-$version