#!/bin/sh

name=`./build | tail -1`
tar=gen/dist/*.tar.gz
tarname=`basename $tar`
scp $tar agpro@agpro:.

ssh agpro@agpro <<EOF
  tar xfz $tarname
  [ -x /home/agpro/app/bin/stop ] && /home/agpro/app/bin/stop
  rm /home/agpro/app
  ln -s /home/agpro/$name /home/agpro/app
  /home/agpro/app/bin/start /home/agpro/conf/config.properties
  rm /home/agpro/*.tar.gz
EOF